"use client";

import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import ToolHeader from "../../components/ToolHeader";
import styles from "./PercentageCalculator.module.css";

type Mode = "of" | "what-percent" | "change" | "increase" | "decrease" | "reverse-increase" | "reverse-decrease" | "markup" | "margin" | "compound";
type FieldKey = "a" | "b" | "c";
type Calculation = { result: number | null; statement: string; formula: string; detail?: string };

type ModeDefinition = { id: Mode; label: string; question: string; fields: Array<{ key: FieldKey; label: string; suffix?: string }> };
const modes: ModeDefinition[] = [
  { id:"of", label:"Percent of a value", question:"What is A% of B?", fields:[{key:"a",label:"Percentage",suffix:"%"},{key:"b",label:"Value"}] },
  { id:"what-percent", label:"Find percentage", question:"A is what percent of B?", fields:[{key:"a",label:"Part"},{key:"b",label:"Whole"}] },
  { id:"change", label:"Percentage change", question:"How much did a value change?", fields:[{key:"a",label:"Original value"},{key:"b",label:"New value"}] },
  { id:"increase", label:"Increase by %", question:"Increase a value by a percentage.", fields:[{key:"a",label:"Original value"},{key:"b",label:"Increase",suffix:"%"}] },
  { id:"decrease", label:"Decrease by %", question:"Decrease a value by a percentage.", fields:[{key:"a",label:"Original value"},{key:"b",label:"Decrease",suffix:"%"}] },
  { id:"reverse-increase", label:"Reverse % increase", question:"Find the value before an increase.", fields:[{key:"a",label:"Final value"},{key:"b",label:"Increase",suffix:"%"}] },
  { id:"reverse-decrease", label:"Reverse % decrease", question:"Find the value before a decrease.", fields:[{key:"a",label:"Final value"},{key:"b",label:"Decrease",suffix:"%"}] },
  { id:"markup", label:"Markup", question:"Find selling price from cost and markup.", fields:[{key:"a",label:"Cost"},{key:"b",label:"Markup",suffix:"%"}] },
  { id:"margin", label:"Profit margin", question:"Find profit margin from cost and selling price.", fields:[{key:"a",label:"Cost"},{key:"b",label:"Selling price"}] },
  { id:"compound", label:"Compound growth", question:"Apply a rate over multiple periods.", fields:[{key:"a",label:"Starting value"},{key:"b",label:"Rate per period",suffix:"%"},{key:"c",label:"Periods"}] },
];
function numeric(value:string){const number=Number(value);return Number.isFinite(number)?number:null}
function format(value:number|null){if(value===null||!Number.isFinite(value))return"—";if(Object.is(value,-0))return"0";const rounded=Number(value.toPrecision(12));return Math.abs(rounded)>=1e9||(Math.abs(rounded)>0&&Math.abs(rounded)<1e-7)?rounded.toExponential(6):String(rounded)}
function calculate(mode:Mode, value:Record<FieldKey,number|null>):Calculation{const{a,b,c}=value;if(a===null||b===null||(mode==="compound"&&c===null))return{result:null,statement:"Enter valid numbers to calculate.",formula:"—"};if(mode==="of")return{result:a*b/100,statement:`${format(a)}% of ${format(b)} equals`,formula:"percentage × value ÷ 100"};if(mode==="what-percent")return b===0?{result:null,statement:"The whole value cannot be zero.",formula:"part ÷ whole × 100"}:{result:a/b*100,statement:`${format(a)} is what percent of ${format(b)}?`,formula:"part ÷ whole × 100"};if(mode==="change")return a===0?{result:null,statement:"The original value cannot be zero for percentage change.",formula:"(new − original) ÷ original × 100"}:{result:(b-a)/a*100,statement:`Change from ${format(a)} to ${format(b)} is`,formula:"(new − original) ÷ original × 100",detail:b>=a?"Increase compared with the original value.":"Decrease compared with the original value."};if(mode==="increase")return{result:a*(1+b/100),statement:`${format(a)} increased by ${format(b)}% equals`,formula:"original × (1 + rate ÷ 100)"};if(mode==="decrease")return{result:a*(1-b/100),statement:`${format(a)} decreased by ${format(b)}% equals`,formula:"original × (1 − rate ÷ 100)"};if(mode==="reverse-increase")return 1+b/100===0?{result:null,statement:"This rate does not produce a valid reverse calculation.",formula:"final ÷ (1 + rate ÷ 100)"}:{result:a/(1+b/100),statement:`Original value before a ${format(b)}% increase was`,formula:"final ÷ (1 + rate ÷ 100)"};if(mode==="reverse-decrease")return 1-b/100===0?{result:null,statement:"A 100% decrease cannot be reversed to one original value.",formula:"final ÷ (1 − rate ÷ 100)"}:{result:a/(1-b/100),statement:`Original value before a ${format(b)}% decrease was`,formula:"final ÷ (1 − rate ÷ 100)"};if(mode==="markup")return{result:a*(1+b/100),statement:`Selling price with ${format(b)}% markup is`,formula:"cost × (1 + markup ÷ 100)"};if(mode==="margin")return b===0?{result:null,statement:"Selling price cannot be zero for profit margin.",formula:"(selling price − cost) ÷ selling price × 100"}:{result:(b-a)/b*100,statement:`Profit margin from cost ${format(a)} and selling price ${format(b)} is`,formula:"(selling price − cost) ÷ selling price × 100"};if(c===null||c<0)return{result:null,statement:"Periods must be zero or greater.",formula:"start × (1 + rate ÷ 100)^periods"};return{result:a*(1+b/100)**c,statement:`${format(a)} growing at ${format(b)}% for ${format(c)} periods equals`,formula:"start × (1 + rate ÷ 100)^periods"}}

export default function PercentageCalculator(){const[mode,setMode]=useState<Mode>("of");const[inputs,setInputs]=useState<Record<FieldKey,string>>({a:"0",b:"0",c:"1"});const[shareMessage,setShareMessage]=useState("");useEffect(()=>{const frame=window.requestAnimationFrame(()=>{const params=new URLSearchParams(window.location.search);const requested=params.get("mode")as Mode|null;if(modes.some((item)=>item.id===requested))setMode(requested as Mode);setInputs((current)=>({a:params.get("a")??current.a,b:params.get("b")??current.b,c:params.get("c")??current.c}))});return()=>window.cancelAnimationFrame(frame)},[]);const active=modes.find((item)=>item.id===mode)??modes[0];const values=useMemo(()=>({a:numeric(inputs.a),b:numeric(inputs.b),c:numeric(inputs.c)}),[inputs]);const result=useMemo(()=>calculate(mode,values),[mode,values]);const resultIsPercent=["what-percent","change","margin"].includes(mode);async function copyShareLink(){const params=new URLSearchParams({mode,a:inputs.a||"0",b:inputs.b||"0",c:inputs.c||"0"});try{await navigator.clipboard.writeText(`${window.location.origin}/percentage-calculator?${params.toString()}`);setShareMessage("Pre-filled share link copied.")}catch{setShareMessage("Copy the current URL from your browser address bar.")}}
return <main id="main-content" className={styles.page}><ToolHeader active="everyday"/><section className={styles.hero}><p>FREE ADVANCED PERCENTAGE CALCULATOR</p><h1>Percentage calculations without a crowded worksheet.</h1><span>Choose one task, enter values, and keep the answer visible. Use dedicated finance tools for profit, interest, loan, and discount calculations.</span></section><section className={styles.workspace}><article className={styles.inputCard}><div className={styles.cardHeading}><div><p>SELECT CALCULATION</p><h2>Percentage workspace</h2></div><span>{modes.length} modes</span></div><label className={styles.modePicker}><span>Calculation type</span><select value={mode} onChange={(event)=>{setMode(event.target.value as Mode);setShareMessage("")}}>{modes.map((item)=><option key={item.id} value={item.id}>{item.label}</option>)}</select><small>{active.question}</small></label><div className={styles.quickModes}>{modes.slice(0,5).map((item)=><button className={mode===item.id?styles.activeQuick:undefined} key={item.id} onClick={()=>{setMode(item.id);setShareMessage("")}} type="button">{item.label}</button>)}</div><div className={styles.fields}>{active.fields.map((field)=><label key={field.key}><span>{field.label}{field.suffix?` (${field.suffix})`:""}</span><input inputMode="decimal" onChange={(event)=>setInputs((current)=>({...current,[field.key]:event.target.value}))} onFocus={(event)=>event.currentTarget.select()} placeholder="0" value={inputs[field.key]}/></label>)}</div><div className={styles.formula}>{result.formula}</div><div className={styles.utilityRow}><span>Share this exact calculation with values pre-filled.</span><button onClick={copyShareLink} type="button">Copy share link</button></div>{shareMessage?<p className={styles.shareMessage}>{shareMessage}</p>:null}</article><aside className={styles.resultCard} aria-live="polite"><p>RESULT</p><h2>{active.label}</h2><span className={styles.statement}>{result.statement}</span><strong>{format(result.result)}{resultIsPercent&&result.result!==null?"%":""}</strong>{result.detail?<b className={styles.detail}>{result.detail}</b>:null}<div className={styles.tip}><p>FINANCE CALCULATORS</p><div className={styles.financeLinks}><Link href="/profit-loss-calculator">Profit & loss →</Link><Link href="/simple-interest-calculator">Simple interest →</Link><Link href="/compound-interest-calculator">Compound interest →</Link><Link href="/loan-calculator">Loan payment →</Link><Link href="/discount-calculator">Discount & tax →</Link></div></div></aside></section></main>}
